name: Dependabot (Auto-merge)

on:
  workflow_run:
    workflows: [CI, CodeQL]
    types:
      - completed

concurrency:
  group: dependabot-automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependabot:
    name: 'Dependabot (auto-merge)'
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}} # Detect that the PR author is dependabot
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL" # Use Github CLI to automatically merge the PR
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.DANIEL_GITHUB_TOKEN }}
          
