name: SSL/TLS Monitor

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

jobs:
  monitor:
    name: SSL/TLS Monitor
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain:
          - codereviews.ai
          - docs.codereviews.ai
    steps:
      - name: Monitor - ${{ matrix.domain }}
        uses: zrosenbauer/action-tls-monitor@main
        with:
          domain: ${{ matrix.domain }}
          expiration_days: "7"
          approved_protocols: TLSv1.2,TLSv1.3
          alert_method: slack
          alert_token: ${{ secrets.SLACK_WEBHOOK_URL_OPS }}

